In [9]:
import numpy as np
import pandas as pd
match_data_input_file = "match_simple.csv"
team_agg_input_file = "team_agg.csv"
training_output_file = "training_data.csv"
test_output_file = "test_data.csv"
# 0 = RED
# 1 = BLUE

In [3]:
teams = pd.read_csv(team_agg_input_file)
teams.head()

,team,elo,event_wins,1_wins,2_wins,3_wins,num_seasons,event_wins_per_season,adjustPoints,autoPoints,...,endgameRobot_HabLevel3,endgameRobot_None,endgameRobot_Unknown,habLineRobot_CrossedHabLineInSandstorm,habLineRobot_CrossedHabLineInTeleop,habLineRobot_None,preMatchLevelRobot_HabLevel1,preMatchLevelRobot_HabLevel2,preMatchLevelRobot_None,preMatchLevelRobot_Unknown
0,frc1,1560,1,0,0,1,24,0.041667,0.0,12.807692,...,0.269231,0.153846,0.0,0.961538,0.038462,0.000000,0.461538,0.538462,0.000000,0.0
1,frc4,1557,2,1,0,1,15,0.133333,0.0,12.720000,...,0.000000,0.360000,0.0,0.960000,0.000000,0.040000,0.040000,0.960000,0.000000,0.0
2,frc8,1572,1,0,0,1,25,0.040000,0.0,13.097561,...,0.000000,0.170732,0.0,1.000000,0.000000,0.000000,0.146341,0.853659,0.000000,0.0
3,frc11,1600,6,2,2,2,24,0.250000,0.0,12.227848,...,0.000000,0.164557,0.0,0.936709,0.037975,0.025316,0.582278,0.392405,0.025316,0.0
4,frc16,1726,17,11,5,1,24,0.708333,0.0,12.365854,...,0.487805,0.121951,0.0,0.951220,0.048780,0.000000,1.000000,0.000000,0.000000,0.0

In [4]:
columns_to_grab = list(teams.columns)[1:]
def getFeaturesForTeam(team):
    team_rows = teams.loc[teams['team'] == team]
    for idx in team_rows.index:
        return list(teams.iloc[idx][columns_to_grab].values)

# METHOD 1 - sum each feature for the alliance (3x feature reduction :D)
def getFeaturesForAllianceM1(teams):
    results = np.array([getFeaturesForTeam(t) for t in teams])
    result = []
    for i in range(len(results[0])):
        col_results = results[:, i]
        result.append(sum(col_results)/len(col_results))
    return result
    
# METHOD 2 - append teams features to eachother
def getFeaturesForAllianceM2(teams):
    results = np.array([getFeaturesForTeam(t) for t in teams])
    return list(np.flatten(results))   # F1, F2    R_F1, R_F2 _      R1_F1, R1_F2, R2_F1, R2_F2, ..

def getFeaturesForMatch(red_teams, blue_teams, winner=None):
    allianceFunc = getFeaturesForAllianceM1 # set this to whatever method you want to use
    if len(red_teams) != 3 or len(blue_teams) != 3:
        print(f"Warning: alliances w/ size ({len(red_teams)}, {len(blue_teams)}) being aggregated.")
    return allianceFunc(red_teams) + allianceFunc(blue_teams) + ([] if winner == None else [winner])

In [5]:
matches = pd.read_csv(match_data_input_file)
print(len(matches.index))
matches.head()

18022

,preChamps,match_key,r1,r2,r3,b1,b2,b3,winner
0,1,2019abca_f1m1,frc2122,frc359,frc6841,frc5015,frc6485,frc7246,0
1,1,2019abca_f1m2,frc2122,frc359,frc6841,frc5015,frc6485,frc7246,0
2,1,2019abca_qf1m1,frc2122,frc359,frc6841,frc1482,frc4010,frc4191,0
3,1,2019abca_qf1m2,frc2122,frc359,frc6841,frc1482,frc4010,frc4191,0
4,1,2019abca_qf2m1,frc4334,frc6351,frc5078,frc3250,frc7591,frc7799,1

In [10]:
# Generating training dataset
training_data = []
for idx in matches.loc[matches['preChamps'] == 1].index:
    match_row = matches.iloc[idx]
    red_teams = [match_row[k] for k in map(lambda a : f'r{a}', range(1, 4))]
    blue_teams = [match_row[k] for k in map(lambda a : f'b{a}', range(1, 4))]
    training_data.append(getFeaturesForMatch(red_teams, blue_teams, match_row['winner']))
test_data = []
for idx in matches.loc[matches['preChamps'] == 0].index:
    match_row = matches.iloc[idx]
    red_teams = [match_row[k] for k in map(lambda a : f'r{a}', range(1, 4))]
    blue_teams = [match_row[k] for k in map(lambda a : f'b{a}', range(1, 4))]
    test_data.append(getFeaturesForMatch(red_teams, blue_teams, match_row['winner']))

In [11]:
for data_obj, output_file in ((training_data, training_output_file), (test_data, test_output_file)):
    writer = open(output_file, 'w')
    for row in data_obj:
        writer.write(','.join(map(str,row)) + '\n')
    writer.close()

In [8]:
training_data = pd.read_csv(training_output_file)
training_data.head()

,1660.0,12.0,5.333333333333333,5.666666666666667,1.0,12.333333333333334,0.6928571428571427,0.0,13.055782602136679,0.004694835680751173,...,0.14020655270655272,0.0.26,0.9743589743589745.2,0.025641025641025644.2,0.0.27,0.4985754985754986,0.5014245014245015,0.0.28,0.0.29,0
0,1660.000000,12.000000,5.333333,5.666667,1.000000,12.333333,0.692857,0.0,13.055783,0.004695,...,0.140207,0.0,0.974359,0.025641,0.000000,0.498575,0.501425,0.000000,0.0,0
1,1660.000000,12.000000,5.333333,5.666667,1.000000,12.333333,0.692857,0.0,13.055783,0.004695,...,0.355072,0.0,0.838969,0.100242,0.060789,0.486715,0.480274,0.033011,0.0,0
2,1660.000000,12.000000,5.333333,5.666667,1.000000,12.333333,0.692857,0.0,13.055783,0.004695,...,0.355072,0.0,0.838969,0.100242,0.060789,0.486715,0.480274,0.033011,0.0,0
3,1549.666667,2.333333,0.666667,1.000000,0.666667,6.666667,0.259259,0.0,12.092857,0.000000,...,0.189934,0.0,0.840931,0.121083,0.037987,0.968186,0.025641,0.006173,0.0,1
4,1549.666667,2.333333,0.666667,1.000000,0.666667,6.666667,0.259259,0.0,12.092857,0.000000,...,0.189934,0.0,0.840931,0.121083,0.037987,0.968186,0.025641,0.006173,0.0,0